//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okurleiga_hf
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApartmentIncident
    {
        public int Id { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public string RegisterName { get; set; }
        public string IncidentInfo { get; set; }
        public bool Status { get; set; }
        public string ContractorWhoFixed { get; set; }
        public Nullable<int> Apartment_Id { get; set; }
    
        public virtual Apartment Apartment { get; set; }
    }
}
