//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okurleiga_hf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apartment()
        {
            this.ApartmentIncidents = new HashSet<ApartmentIncident>();
            this.ApartmentOwners = new HashSet<ApartmentOwner>();
            this.Rents = new HashSet<Rent>();
        }
    
        public int Id { get; set; }
        public System.DateTime RegisteredAt { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int Zip { get; set; }
        public int Bedroom { get; set; }
        public int Bathroom { get; set; }
        public int Size { get; set; }
        public int RentPrize { get; set; }
        public bool Available { get; set; }
        public string RentType { get; set; }
        public bool Garage { get; set; }
        public bool Smoking { get; set; }
        public bool Pet { get; set; }
        public string Type { get; set; }
        public Nullable<int> ApartmentOwner_Id { get; set; }
        public Nullable<int> Owner_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApartmentIncident> ApartmentIncidents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApartmentOwner> ApartmentOwners { get; set; }
        public virtual ApartmentOwner ApartmentOwner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rent> Rents { get; set; }
    }
}
